security:
  basic:
    enabled: false

management:
  security:
    enabled: false
logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

logging:
  level:
    io:
      pivotal: INFO

quoteServiceURL: http://quote-service-qa.cfapps.io/quote